default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: Currency_development

test:
  <<: *default
  database: Currency_test

production:
  <<: *default
  database: Currency_production
  username: Currency
  url: <%= ENV['DATABASE_URL'] %>
